services:
  homelynx-bot:
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./docker-compose.yaml
        - action: rebuild
          path: ./docker-compose.dev.yaml
