from __future__ import annotations

ADMIN_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Homelynx Admin</title><style>
:root{--bg:#050807;--panel:#0b1110;--line:#214334;--text:#d8ffe8;--muted:#88a997;--green:#3cff8f;--cyan:#5ce1ff;--red:#ff5c7a;--yellow:#ffd166}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 5%,rgba(60,255,143,.15),transparent 30%),#050807;color:var(--text);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}main{width:min(1400px,calc(100% - 24px));margin:auto;padding:18px 0}.top,.panel{border:1px solid var(--line);background:rgba(11,17,16,.9);padding:14px}.title{font-size:34px;color:var(--green);font-weight:900;text-transform:uppercase}.title:before{content:"> ";color:var(--cyan)}.grid{display:grid;grid-template-columns:430px 1fr;gap:14px;margin-top:14px}.card{border:1px solid var(--line);padding:10px;margin:8px 0;background:#07100c}.row{display:flex;align-items:center;justify-content:space-between;gap:8px}.muted{color:var(--muted);font-size:12px}.ok{color:var(--green)}.bad{color:var(--red)}.warn{color:var(--yellow)}button,select{background:#07100c;color:var(--text);border:1px solid var(--line);padding:8px;font:inherit;cursor:pointer}button:hover{border-color:var(--green)}pre{white-space:pre-wrap;word-break:break-word;background:#020504;border:1px solid var(--line);padding:12px;min-height:520px;max-height:70vh;overflow:auto}.pill{border:1px solid var(--line);padding:2px 7px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}a{color:var(--cyan)}@media(max-width:900px){.grid{grid-template-columns:1fr}}
</style></head><body><main><section class="top"><div class="title">Admin cockpit</div><div class="muted"><a href="/">portal</a> / <a href="/llm">llm audit</a> / local Docker control</div></section><section class="grid"><aside class="panel"><h3>Modules</h3><div id="mods"></div><h3>Services</h3><div id="services"></div></aside><section class="panel"><div class="tabs"><select id="logsvc"></select><button onclick="loadLogs()">logs</button><button onclick="loadCaps()">capabilities</button><button onclick="refresh()">refresh</button></div><pre id="log">Select service logs.</pre></section></section></main><script>
const esc=s=>(s??'').toString().replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));let state={};
function csrfHeaders(extra={}){let token=localStorage.getItem('portalCsrfToken')||'';if(!token){token=prompt('CSRF token')||'';if(token)localStorage.setItem('portalCsrfToken',token)}return {...extra,'X-Portal-CSRF':token}}
async function refresh(){const r=await fetch('/api/admin/status');state=await r.json();render()}
function cls(x){return x==='running'?'ok':(x==='exited'||x==='missing'?'bad':'warn')}
function render(){mods.innerHTML=(state.modules||[]).map(m=>`<div class="card"><div class="row"><b>${esc(m.name)}</b><span class="pill ${m.enabled?'ok':'bad'}">${m.enabled?'on':'off'}</span></div><div class="muted">${esc(m.key)}=${esc(m.value)}</div><button onclick="setModule('${m.name}',${!m.enabled})">turn ${m.enabled?'off':'on'}</button></div>`).join('');services.innerHTML=(state.containers||[]).map(s=>`<div class="card"><div class="row"><b>${esc(s.service)}</b><span class="pill ${cls(s.state)}">${esc(s.state)}</span></div><div class="muted">${esc(s.status)}</div><button onclick="act('${s.service}','restart')">restart</button> <button onclick="act('${s.service}','start')">start</button> <button onclick="act('${s.service}','stop')">stop</button> <button onclick="pickLogs('${s.service}')">logs</button></div>`).join('');logsvc.innerHTML=(state.containers||[]).map(s=>`<option value="${esc(s.service)}">${esc(s.service)}</option>`).join('')}
async function setModule(m,en){await fetch('/api/admin/module/'+m,{method:'POST',headers:csrfHeaders({'Content-Type':'application/json'}),body:JSON.stringify({enabled:en})});await refresh()}
async function act(s,a){await fetch(`/api/admin/service/${s}/${a}`,{method:'POST',headers:csrfHeaders()});setTimeout(refresh,900)}
function pickLogs(s){logsvc.value=s;loadLogs()}async function loadLogs(){log.textContent='loading...';const r=await fetch('/api/admin/logs/'+logsvc.value+'?tail=250');log.textContent=await r.text()}
async function loadCaps(){log.textContent='loading...';const r=await fetch('/api/admin/capabilities');const data=await r.json();const groups=data.groups||{};const parts=[`Capabilities: ${data.count||0}`];for(const [module,items] of Object.entries(groups)){parts.push(`\n[${module}]`);for(const item of items||[]){parts.push(`- ${item.command||item.name} | ${item.permission||'ALL'} | ${item.risk||'safe'} | ${item.description||''}`)}}log.textContent=parts.join('\n')}
refresh();setInterval(refresh,10000)
</script></body></html>'''

LLM_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Homelynx Activity Audit</title>
  <style>
    :root{--bg:#050807;--panel:#0b1110;--panel2:#101a16;--line:#214334;--text:#d8ffe8;--muted:#88a997;--green:#3cff8f;--cyan:#5ce1ff;--red:#ff5c7a;--yellow:#ffd166}
    *{box-sizing:border-box} body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% 8%,rgba(60,255,143,.14),transparent 32%),linear-gradient(180deg,#050807,#07100c);color:var(--text);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace}
    main{width:min(1380px,calc(100% - 24px));margin:auto;padding:18px 0 28px}.top{border:1px solid var(--line);background:rgba(11,17,16,.9);padding:16px;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.title{color:var(--green);font-size:clamp(24px,5vw,38px);font-weight:900;text-transform:uppercase}.title:before{content:"> ";color:var(--cyan)}.meta{color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:390px 1fr;gap:14px;margin-top:14px}.panel{border:1px solid var(--line);background:rgba(11,17,16,.88);padding:14px;min-height:120px}.filters{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}input,select,button{background:#07100c;color:var(--text);border:1px solid var(--line);padding:10px;font:inherit}button{cursor:pointer;color:var(--green);font-weight:800}button:hover{border-color:var(--green)}.statrow{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.stat{border:1px solid var(--line);background:var(--panel2);padding:10px}.stat b{display:block;color:var(--green);font-size:22px}.item{border:1px solid var(--line);background:#08100d;margin-bottom:8px;padding:10px;cursor:pointer}.item:hover,.item.active{border-color:var(--green)}.item .h{display:flex;justify-content:space-between;gap:8px}.badge{padding:2px 7px;border:1px solid var(--line);color:var(--cyan);font-size:12px}.badge.error{color:var(--red)}.badge.success{color:var(--green)}.badge.partial,.badge.finalized{color:var(--yellow)}.small{color:var(--muted);font-size:12px;line-height:1.45}.detail-head{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:10px}.kv{border:1px solid var(--line);padding:9px;background:var(--panel2)}.kv span{display:block;color:var(--muted);font-size:11px;text-transform:uppercase}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.tab{border:1px solid var(--line);padding:8px 10px;color:var(--muted);cursor:pointer}.tab.active{color:var(--green);border-color:var(--green)}pre{white-space:pre-wrap;word-break:break-word;border:1px solid var(--line);background:#030605;padding:12px;min-height:360px;max-height:68vh;overflow:auto;color:#cfffdd}.empty{color:var(--muted);padding:24px;border:1px dashed var(--line)}a{color:var(--cyan)}@media(max-width:900px){.grid{grid-template-columns:1fr}.detail-head,.statrow{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr}}
  </style>
</head>
<body><main>
  <section class="top"><div><div class="title">Activity audit</div><div class="meta">Categorized history for LLM, surveillance, search, downloads, TTS, and capability execution</div></div><div class="meta"><a href="/">portal</a> / SQLite / retained by policy</div></section>
  <section class="grid">
    <aside class="panel"><div class="filters"><input id="q" placeholder="search"><select id="category"><option value="">category: all</option><option value="surveillance">surveillance</option><option value="downloads">downloads</option><option value="search">search</option><option value="llm">llm</option><option value="capability">capability</option><option value="tts">tts</option><option value="coords">coords</option><option value="system">system</option></select><select id="status"><option value="">status: all</option><option>success</option><option>error</option><option>empty</option><option>partial</option><option>finalized</option></select><input id="service" placeholder="service"><input id="feature" placeholder="feature"><button onclick="loadAll()">refresh</button><button onclick="clearFilters()">clear</button></div><div class="statrow"><div class="stat"><span class="small">entries</span><b id="total">0</b></div><div class="stat"><span class="small">avg ms</span><b id="avg">0</b></div><div class="stat"><span class="small">last</span><b id="last">n/a</b></div></div><div id="cats" class="small"></div><div id="items"></div></aside>
    <section class="panel"><div id="detail" class="empty">Select an audit entry.</div></section>
  </section>
</main><script>
let activeId=null, activeTab='prompt', current=null;
const esc=s=>(s??'').toString().replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function qs(){const p=new URLSearchParams();['q','category','status','service','feature'].forEach(id=>{const v=document.getElementById(id).value.trim(); if(v)p.set(id,v)});p.set('limit','150');return p.toString()}
async function loadStats(){const r=await fetch('/api/llm/stats');const j=await r.json();const t=j.totals||{};document.getElementById('total').textContent=t.count||0;document.getElementById('avg').textContent=Math.round(t.avg_ms||0);document.getElementById('last').textContent=(t.last_at||'n/a').slice(5,16);document.getElementById('cats').innerHTML=(j.by_category||[]).map(c=>`<button onclick="document.getElementById('category').value='${esc(c.category)}';loadAll()">${esc(c.category)} ${c.count}</button>`).join(' ')}
async function loadList(){const r=await fetch('/api/llm/history?'+qs());const j=await r.json();const el=document.getElementById('items');if(!j.items?.length){el.innerHTML='<div class="empty">No activity entries found.</div>';return}el.innerHTML=j.items.map(x=>`<div class="item ${x.id===activeId?'active':''}" onclick="loadDetail(${x.id})"><div class="h"><b>#${x.id} ${esc(x.feature)}</b><span><span class="badge">${esc(x.category||'system')}</span> <span class="badge ${esc(x.status)}">${esc(x.status)}</span></span></div><div class="small">${esc(x.service)}${x.model?' / '+esc(x.model):''} / ${Math.round(x.duration_ms||0)}ms</div><div class="small">${esc(x.created_at)} ${x.subject_id?' / '+esc(x.subject_id):''}</div>${x.error?`<div class="small" style="color:var(--red)">${esc(x.error).slice(0,160)}</div>`:''}</div>`).join('')}
async function loadDetail(id){activeId=id;activeTab='prompt';await loadList();const r=await fetch('/api/llm/history/'+id);const j=await r.json();current=j.item;renderDetail()}
function valForTab(){if(!current)return'';return current[activeTab]||''}
function renderDetail(){if(!current)return;const tabs=['prompt','request_json','raw_response','parsed_response','error','metadata_json'];document.getElementById('detail').innerHTML=`<div class="detail-head"><div class="kv"><span>category</span>${esc(current.category||'system')}</div><div class="kv"><span>service</span>${esc(current.service)}</div><div class="kv"><span>feature</span>${esc(current.feature)}</div><div class="kv"><span>duration</span>${Math.round(current.duration_ms||0)}ms</div><div class="kv"><span>subject</span>${esc(current.subject_type||'')} ${esc(current.subject_id||'')}</div><div class="kv"><span>status</span>${esc(current.status)}</div><div class="kv"><span>created</span>${esc(current.created_at)}</div><div class="kv"><span>model/tokens</span>${esc(current.model||'n/a')} ${esc(current.prompt_eval_count||'')} / ${esc(current.eval_count||'')}</div></div><div class="tabs">${tabs.map(t=>`<div class="tab ${t===activeTab?'active':''}" onclick="activeTab='${t}';renderDetail()">${t}</div>`).join('')}</div><pre>${esc(valForTab())}</pre>`}
function clearFilters(){['q','category','status','service','feature'].forEach(id=>document.getElementById(id).value='');loadAll()} async function loadAll(){await loadStats();await loadList()} loadAll(); setInterval(loadAll,15000);
</script></body></html>'''
